### ISSUE TITLE
Java runtime could not be located

### ISSUE THREAD

**Issue by yck011522** [fabioz/vscode-pydev-info#6]
I'm using VS Code 1.45.0 on Windows 10 to develop in python.
Just installed pydev extension to give it a try.
Been struggling for an hour to resolve the error "Java runtime could not be located"
I have tried to install jdk1.8.0_251 and jre1.8.0_251 and configured in settings.json

1. "python.pydev.java.home": "C:\\Program Files\\Java\\jdk1.8.0_251"
2. "python.pydev.java.home": "C:\\Program Files\\Java\\jre1.8.0_251"
3.  Leave this setting out.

None of them worked for me. The error is still there. It is not clear how to proceed. 

I can confirm that `java -version` works in my environment in project directory:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by fabioz** [comment]
Sorry about that. The issue was that it was looking for `pydev.java.home` instead of `python.pydev.java.home`. 0.2.1 (just released) fixes this.
